# Generated by Django 3.2.4 on 2021-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('NumeroIden', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Identificación')),
                ('NombreCompleto', models.CharField(max_length=30, verbose_name='Nombre del Proveedor')),
                ('Telefono', models.IntegerField(max_length=9, verbose_name='Numero Telefonico')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección Proveedor')),
                ('email', models.EmailField(max_length=50, verbose_name='Email de proveedor')),
                ('Pais', models.CharField(max_length=30, verbose_name='País del proveedor')),
                ('Pass', models.CharField(max_length=10, verbose_name='Contraseña Proveedor')),
            ],
        ),
    ]
