# Generated by Django 3.2.4 on 2021-07-02 16:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0003_alter_proveedor_numeroiden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='NombreCompleto',
            field=models.CharField(max_length=30, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Telefono',
            field=phone_field.models.PhoneField(blank=True, help_text='Numero de Contacto proveedor', max_length=31),
        ),
    ]
