# Generated by Django 3.1 on 2021-07-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0005_proveedor_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='TipMoneda',
            field=models.IntegerField(choices=[[0, 'Dolar'], [1, 'Peso Chileno']], default=0),
            preserve_default=False,
        ),
    ]
