# Generated by Django 3.1 on 2021-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0006_proveedor_tipmoneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Fotografia',
            field=models.ImageField(default=1, upload_to='proveedores'),
            preserve_default=False,
        ),
    ]
