# Generated by Django 3.1 on 2021-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0007_auto_20210704_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Fotografia',
            field=models.ImageField(null=True, upload_to='proveedores'),
        ),
    ]
